import Head from 'next/head'
import { useEffect, useState } from 'react';
import { api } from '../services/api';
import styles from '../styles/Home.module.css'

type Transacition = {
  id: string,
  title: string,
  description: string,
  status: string,
  amount: number,
  date: string,
  from: string,
  to: string
}

export default function Home() {
  const defaultTransction = {
    "id": "",
    "title": "",
    "description": "",
    "status": "",
    "amount": 0,
    "date": "",
    "from": "",
    "to": ""
  }
  const [transctions, setTransctions] = useState<Transacition[]>([defaultTransction])

  useEffect(() => {
    api.get('/')
      .then((res) => {
        const data =  res.data;
        setTransctions(data);
      });
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Warren Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <table>
          <tr>
            <th>ID</th>
            <th>title</th> 
            <th>Description</th>
            <th>Status</th>
            <th>Amount</th>
            <th>Date</th>
            <th>From</th>
            <th>To</th>
          </tr>
            {transctions.map((props: Transacition) => {
              return (
                <tr key={props.id} onClick={() => showDetails(props.id)}>
                  <td>{props.id}</td>
                  <td>{props.title}</td> 
                  <td>{props.description}</td>
                  <td>{props.status}</td>
                  <td>{props.amount}</td>
                  <td>{props.date}</td>
                  <td>{props.from}</td>
                  <td>{props.to}</td>
                </tr>         
              )
            })}
        </table>
      </main>
    </div>
  )
}
